### ISSUE TITLE
2 general requests | 2 bugs

### ISSUE THREAD

**Issue by ManticSic** [emalikterzi/angular-owl-carousel-2#1]
Hey,
thx for providing a working  owl carousel directive.

Some general requests
+ could you add a licence please?
+ could you add this to npm please?

---

... and now some bugs
- currently you cannot attach callbacks (missing values in owlProperties list)
- you cannot trigger  an event programmatically (no access to owl carousel api)

_Pullrequest is on the way :)_

update:
Pull request #2

**Comment by emalikterzi** [comment]
@ManticSic hey there , thank you for pull request. i also added Mit licence and npm support.
