### ISSUE TITLE
Error: [$parse:isecdom]

### ISSUE THREAD

**Issue by khraibani** [emalikterzi/angular-owl-carousel-2#3]
Hi, 
I am getting the below error (i am using angular 1.5.1)

<img width="831" alt="screen shot 2017-01-28 at 21 33 19" src="https://cloud.githubusercontent.com/assets/4085627/22399993/6c3a529c-e5a1-11e6-92c7-47634f59519d.png">
<img width="1020" alt="screen shot 2017-01-28 at 21 34 00" src="https://cloud.githubusercontent.com/assets/4085627/22399999/92dce40a-e5a1-11e6-9df3-230b627d7615.png">

<img width="1261" alt="screen shot 2017-01-28 at 21 28 11" src="https://cloud.githubusercontent.com/assets/4085627/22399975/e16876ee-e5a0-11e6-9feb-79dfc755ecd4.png">

**Comment by emalikterzi** [comment]
@khraibani  it seems this is causing cause  you're using very old version of angular. this is causing because i'm trying to pass element object from link function . 

i updated source code

try to reinstall with bower install ( after deleting bower folder )

give it try and let me know  .

**Comment by khraibani** [comment]
Thanks for the swift fix, all working!
