### ISSUE TITLE
Missing option `autoHeight`

### ISSUE THREAD

**Issue by r3wt** [emalikterzi/angular-owl-carousel-2#4]
the option is undocumented on the owlCarousel2 website for some reason, but it still works.

**Comment by emalikterzi** [comment]
@r3wt yeah you're right i couldn't find property neither . i think that is not an issue .

**Comment by r3wt** [comment]
it actually is an issue, since your module does not set the property unless it exists in the array.

**Comment by r3wt** [comment]
simply adding it to the array and my slider works as expected.
