### ISSUE TITLE
expose init() and destroy() in ready() function

### ISSUE THREAD

**Issue by r3wt** [emalikterzi/angular-owl-carousel-2#6]
As you can see, anything that is animated will cause the autoHeight to never adjust the carousel. can be worked around by exposing these methods in someway, possibly by providing it to the ready() listener

![image](https://cloud.githubusercontent.com/assets/4483325/23225661/4bc3b0b6-f8f8-11e6-97ac-58ea9873feea.png)

**Comment by emalikterzi** [comment]
@r3wt you can edit properties for event methods. 
please check https://owlcarousel2.github.io/OwlCarousel2/docs/api-events.html

no need for extra change.
