### ISSUE TITLE
lazyloading images isn't supported

### ISSUE THREAD

**Issue by r3wt** [emalikterzi/angular-owl-carousel-2#7]

**Comment by emalikterzi** [comment]
@r3wt  added lazy load example , should be work right now.

**Comment by r3wt** [comment]
No dice on either issue. I may take a crack at it tomorrow after work, time permitting.

**Comment by emalikterzi** [comment]
@r3wt  hi , i couldn't simulate error . can you provide an example .

( sorry for late response )

**Comment by r3wt** [comment]
@emalikterzi i will try to get an example for you soon. right now i am busy at work, and i also need to submit fixes upstream to owlcarousel on unrelated matters. i'm going to check while i'm at it, and see if i can fix it upstream as well.
