### ISSUE TITLE
Some times the carousel isn't initialized

### ISSUE THREAD

**Issue by nachtwandler** [emalikterzi/angular-owl-carousel-2#9]
Hey,

I've got the problem, that some times the carousel isn't initialized after route change. Some times it is.
Then, the carousel isn't working and the carousel-items just shown among each other

**Comment by emalikterzi** [comment]
@nachtwandler how can i simulate this :) . can you provide example.

**Comment by nachtwandler** [comment]
@emalikterzi I'va a REST api, which provided image URLs I use in the slider. If it loads fast, it works but if the api takes a second it seems it doesn't initialize. Can i trigger the reinitialize? So I can do it after the promise is resolved?

**Comment by r3wt** [comment]
@nachtwandler one solution might be to use ng-if to prevent the directive from rendering initially like so:

controller:
`
$scope.owlSlidesReady = false;
`
view:
`<div ng-if="owlSlidesReady">`

when data finish loading:

`$scope.owlSlidesReady = true`

i think this should delay the binding of the directive until the slides are loaded, solving your problem.

**Comment by emalikterzi** [comment]
@nachtwandler just using owl-items attribute should be fine. directive watching changes on owl-items

`<ng-owl-carouse> owl-items="items"`
